version: '3.8'

services:
  veritamom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veritamom-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - veritamom-db:/app/prisma
    networks:
      - webnet

volumes:
  veritamom-db:
    driver: local

networks:
  webnet:
    external: true
